### ISSUE TITLE
Promise based error handling

### ISSUE THREAD

**Issue by orangemug** [orangemug/isorouter#14]
Errors thrown in promise chain should be handled by error handlers

```
app.use(function(err, req, res, next) {
  console.error(err);
  next();
});

// Errors thrown from 'db.conn()' should be handled by the above
app.get("/", function(req, res) {
  return db.conn()
    .then(function() { /* do something */ })
});
```

**Comment by oliverbrooks** [comment]
I think this would break express compatibility which would limit the application of this handy promise handling.

For promise support perhaps something like a middleware extension plugin. Promise support might be added via extending the `next` function.  For example:

``` js
const isorouter = require("isorouter");
const isorouterPromised = require("isorouter-promised");

const app = isorouter();

// Mount promise extension
app.use(isorouterPromised);

app.get("/", function (req, res) {
  const myPromise = Promise.resolve("fish").then(function (thing) {
    res.body = thing;
  });
  next.promised(myPromise);
}
```

`next.promised` could call next `next()` on success or `next(err)` on failure. 

Hopefully that should work with express as well.  

Not sure what the logistics of extending `next` are in express but if not could extend `res` and call `res.promised`?

**Comment by orangemug** [comment]
Yeah you're right breaking compatibility is a bad idea, lets close this one. Sounds like something for an express helper that just worked with isorouter because they have the same API

Thanks @oliverbrooks
