### ISSUE TITLE
Render idea

### ISSUE THREAD

**Issue by oliverbrooks** [orangemug/isorouter#2]
Would be nice to be able to register an isomorphic render function which can then be called with `render` inside the handlers.

``` js
const ReactDOMServer = require("react-dom/server");
const ReactDomClient = require("react-dom");

// In the setup
isoRouter({
  injectNode: ".app",
  browserRender: function (reactComponent) {
    const el = document.querySelector("." + this.inject);
    const element = React.createElement(reactcomponent);
    ReactDomClient.render(element, el);
  },
  serverRender: function (reactComponent) {
    const element = React.createElement(reactcomponent);
    const html = ReactDOM.renderToString(element);
    res.send(html);
  }
});

// In the app
const component = require("lib/component");
router.get("/fish-badgers", function (req, res) {
  res.render(component({
    key1: "Fish",
    key2: "Badger"
  });
});
```

**Comment by orangemug** [comment]
This should be possible with middleware at the moment. Have you got a use case as to why you wouldn't want to use a middleware? Something along the lines of

```
app.use("/", function(req, res, next) {res.render = renderFn; next();})
```

**Comment by oliverbrooks** [comment]
My thinking was that isorouter should match an express router as much as possible. This is the way you render something from an express router.

Rendering is also a very much required function for an isomorphic app. Isorouter providing an isomorphic render therefore ensures the developer doesn't mix client/server specific code into their isomorphic code.  I feel isorouter should either have a provision for rendering or should strongly suggest a system for doing so.  I figured registering client/server functions would be the most flexible way of doing this.

What may be even more expressy is to register the renderer as an engine to ease modularisation and match [express engines](http://expressjs.com/advanced/developing-template-engines.html)

**Comment by orangemug** [comment]
I guess I'd like this to stay a subset of express for now, middleware seems to get us to a render function easiest, to implement engines sounds like a lot more work I think we should work on other things at this time.

Closing for now, although happy to hear other comments
